workflows:
  android:
   name: Android Workflow
   environment:
     flutter: stable
   scripts:
     - name: Get dependencies
       script: |
         cd test_app 
         flutter pub get
     - name: build APK
       script: |
         cd test_app
         flutter build apk 
     - name: Debug output
       script: |
         echo "Listing APK folder..."
         ls -al test_app/build/app/outputs/flutter-apk
   artifacts:
     - test_app/build/app/outputs/flutter-apk/*.apk