workflows:
  android:
   name: Android Workflow
   environment:
     flutter: stable
   scripts:
     - name: Get dependencies
       script:
         cd test_app 
         flutter pub get
     - name: build APK
       script:
         cd test_app
         flutter build apk  
   artifacts:
     - build/app/outputs/flutter-apk/app-release.apk