workflows:
     android:
       name: Android Workflow
         environment:
           flutter: stable
            scripts:
            -name: Get dependences
            script: flutter pub get
            -name: build APK
            script: flutter build apk